[package]
name = "etm"
description = "easy tcp messaging"
version = "0.12.0"
authors = ["Mathias Kraus <mathias.kraus@bobedibob.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1"
