[package]
name = "etm"
description = "easy tcp messaging"
version = "0.14.2"
authors = ["Mathias »Bob« Kraus <elboberido@m-hias.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
