[package]
name = "etm"
description = "easy tcp messaging"
version = "0.14.2"
authors = ["Mathias Kraus <mathias.kraus@bobedibob.de>"]
edition = "2018"

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
